name: Run latest snowblower

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '30 * * * *'

jobs:
  run:
    uses: Edivad99/snowblower-run/.github/workflows/snowblower.yml@main
    concurrency:
      group: snowman-releases
      cancel-in-progress: false
    with:
      branch: dev
      snowblower-version: 2.0.9
    secrets:
      SNOWLANCE_PRIVATE_KEY: ${{ secrets.SNOWLANCE_PRIVATE_KEY }}
